### PR TITLE
import  from .paper instead of paper.paper

### PR DESCRIPTION
**Pull request by cekees**
I have to do something like this to  prevent error on import

### CODE REVIEW

**Comment by jdfreder** [comment]
@cekees have you tried this import from outside of the papershape repo?  It's relative so I don't think it'll work.  Maybe you are having installation problems?  I remember pip didn't behave well with Jupyter pip on your machine, and we found using `python setup.py install` seemed to work.

**Comment by cekees** [comment]
OK, to be honest the relative path stuff came along after I came of age in python, but I think you actually want a relative path here.  I've wiped  out the package  and reinstalled  twice, once  using `python setup.py install`  and one with `pip install -e .`. Both give

```
from paper.paper import *
```

ImportError: No module named paper

regardless  of where I start python, while the relative import works  regardless of install method  or working directory.

**Comment by jdfreder** [comment]
Whoops, didn't see you were doing this in init.py!  It works : )  Thanks!

**Comment by jdfreder** [comment]
Ah, I see, this is a Python2/3 thing.  I've been using 3, which doesn't complain about this.  I bet that's where other problem is...  Looking.

**Pull request merged**
